#!/usr/bin/env python3
"""
Setup script to configure environment variables for the FUT QA Assistant
"""

import os
import sys

def setup_environment():
    """Interactive setup for environment variables"""
    print("🔧 FUT QA Assistant - Environment Setup")
    print("=" * 50)
    print("This script will help you set up your API keys securely.")
    print("Your keys will be stored in a .env file (not committed to git)")
    print()
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    
    # Collect API keys
    print("Please enter your API keys (press Enter to skip):")
    print()
    
    env_vars = {}
    
    # OpenAI API Key
    openai_key = input("OpenAI API Key (https://platform.openai.com/api-keys): ").strip()
    if openai_key:
        env_vars['OPENAI_API_KEY'] = openai_key
    
    # Google Gemini API Key
    gemini_key = input("Google Gemini API Key (https://makersuite.google.com/app/apikey): ").strip()
    if gemini_key:
        env_vars['GEMINI_API_KEY'] = gemini_key
    
    # Hugging Face API Key
    hf_key = input("Hugging Face API Key (https://huggingface.co/settings/tokens): ").strip()
    if hf_key:
        env_vars['HUGGINGFACE_API_KEY'] = hf_key
    
    # Groq API Key
    groq_key = input("Groq API Key (https://console.groq.com/keys): ").strip()
    if groq_key:
        env_vars['GROQ_API_KEY'] = groq_key
    
    # Search API Key (optional)
    search_key = input("Search API Key (optional): ").strip()
    if search_key:
        env_vars['SEARCH_API_KEY'] = search_key
    
    # Write .env file
    if env_vars:
        with open('.env', 'w') as f:
            f.write("# FUT QA Assistant - Environment Variables\n")
            f.write("# Generated by setup_environment.py\n\n")
            for key, value in env_vars.items():
                f.write(f"{key}={value}\n")
        
        print(f"\n✅ Environment file created with {len(env_vars)} API keys!")
        print("🔒 Your .env file is automatically ignored by git for security.")
    else:
        print("\n⚠️  No API keys provided. You can run this script again later.")
    
    print("\n📝 Next steps:")
    print("1. Make sure your .env file is in the project root")
    print("2. Test your setup by running: python test_external_api.py")
    print("3. Start the application: python backend/app.py")

if __name__ == "__main__":
    setup_environment()
